names:
    teacher: 'Віктор Плекач'
    students:
        - "Алла Цимбаленко"
        - "Ілона Безрукова"
        - "Олександр Черешня"
        - "Тимофій Небенко"
        - "Прокіп Боровенко"
        - "Микола Прокопенко"
        - "Антон Картон"
        - "Олександр Девелопенко"
        - "Євгеній Петросяненко"
        - "Євдокимія Кац"
        - "Яків Ніякий"
        - "Анатолій Вишня"
        - "Наталка Полтавка"
        - "Степан Ломака"
        - "Омелян Косовороткін"
