names:
    teacher: 'Віктор Плекач'
    students:
        - "Алла Цимбаленко"
        - "Дар'я Підгорняк"
        - "Дар'я Підгорняк"
        - "Тимофій Небенко"
        - "Дар'я Підгорняк"
        - "Микола Прокопенко"
        - "Дар'я Підгорняк"
        - "Дар'я Підгорняк"
        - "Дар'я Підгорняк"
        - "Євдокимія Кац"
        - "Яків Ніякий"
        - "Анатолій Вишня"
        - "Наталка Полтавка"
        - "Степан Ломака"
        - "Омелян Косовороткін"
    evil-student: "Дар'я Підгорняк"
