names:
    teacher: 'Віктор Плекач'
    students:
        - "Алла Цимбаленко"
        - "Ілона Безрукова"
        - "Олександр Черешня"
        - "Тимофій Небенко"
        - "Прокіп Боровенко"
        - "Микола Прокопенко"
        - "Антон Картон"
        - "Олександр Девелопенко"
        - "Євгеній Петросяненко"
        - "Євдокимія Кац"
        - "Яків Ніякий"
        - "Анатолій Вишня"
        - "Наталка Полтавка"
        - "Степан Ломака"
        - "Омелян Косовороткін"
    evil-student: "Діана Підгорна"
params:
    normal-dps-reject: 150
    normal-dps-timeout: 200
    evil-dps-reject: 200
    evil-dps-timeout: 300
    evil-heal: 50
    normal-heal: 25
    normal-time: 30
    evil-time: 7
    evil-student-spawn-chance: 15
    spawner-interval : 2000
    event-spawn-chance : 40